# Generated by Django 2.2 on 2020-04-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200418_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text1',
            new_name='text',
        ),
    ]
